# Autogenerated wrapper script for Musica_jll for aarch64-apple-darwin-julia_version+1.10.0
export libmechanism_configuration, libmusica, libmusica_julia, libyaml_cpp

using libcxxwrap_julia_jll
JLLWrappers.@generate_wrapper_header("Musica")
JLLWrappers.@declare_library_product(libmechanism_configuration, "@rpath/libmechanism_configuration.1.dylib")
JLLWrappers.@declare_library_product(libmusica, "@rpath/libmusica.0.dylib")
JLLWrappers.@declare_library_product(libmusica_julia, "@rpath/libmusica_julia.dylib")
JLLWrappers.@declare_library_product(libyaml_cpp, "@rpath/libyaml-cpp.0.8.dylib")
function __init__()
    JLLWrappers.@generate_init_header(libcxxwrap_julia_jll)
    JLLWrappers.@init_library_product(
        libmechanism_configuration,
        "lib/libmechanism_configuration.1.1.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmusica,
        "lib/libmusica.0.15.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmusica_julia,
        "lib/libmusica_julia.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libyaml_cpp,
        "lib/libyaml-cpp.0.8.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
