# Autogenerated wrapper script for Musica_jll for i686-w64-mingw32-cxx11-julia_version+1.14.0
export libmechanism_configuration, libmusica, libmusica_julia, libyaml_cpp

using libcxxwrap_julia_jll
JLLWrappers.@generate_wrapper_header("Musica")
JLLWrappers.@declare_library_product(libmechanism_configuration, "libmechanism_configuration.dll")
JLLWrappers.@declare_library_product(libmusica, "libmusica.dll")
JLLWrappers.@declare_library_product(libmusica_julia, "libmusica_julia.dll")
JLLWrappers.@declare_library_product(libyaml_cpp, "libyaml-cpp.dll")
function __init__()
    JLLWrappers.@generate_init_header(libcxxwrap_julia_jll)
    JLLWrappers.@init_library_product(
        libmechanism_configuration,
        "bin\\libmechanism_configuration.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmusica,
        "bin\\libmusica.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmusica_julia,
        "bin\\libmusica_julia.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libyaml_cpp,
        "bin\\libyaml-cpp.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
