# Autogenerated wrapper script for Musica_jll for x86_64-unknown-freebsd
export libmechanism_configuration, libmusica, libmusica_julia, libyaml_cpp

using libcxxwrap_julia_jll
JLLWrappers.@generate_wrapper_header("Musica")
JLLWrappers.@declare_library_product(libmechanism_configuration, "libmechanism_configuration.so.1")
JLLWrappers.@declare_library_product(libmusica, "libmusica.so.0")
JLLWrappers.@declare_library_product(libmusica_julia, "libmusica_julia.so")
JLLWrappers.@declare_library_product(libyaml_cpp, "libyaml-cpp.so.0.8")
function __init__()
    JLLWrappers.@generate_init_header(libcxxwrap_julia_jll)
    JLLWrappers.@init_library_product(
        libmechanism_configuration,
        "lib/libmechanism_configuration.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmusica,
        "lib/libmusica.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmusica_julia,
        "lib/libmusica_julia.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libyaml_cpp,
        "lib/libyaml-cpp.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
